

export const blackListTypes = [
  "DataView",
  "AggregateError",
  "readonly T[]",
  "Math",
  "Date",
  "RegExp",
  "Error",
  "EvalError",
  "RangeError",
  "ReferenceError",
  "SyntaxError",
  "TypeError",
  "URIError",
  "JSON",
  "ArrayBuffer",
  "Int8Array",
  "Uint8Array",
  "Uint8ClampedArray",
  "Int16Array",
  "Uint16Array",
  "Int32Array",
  "Uint32Array",
  "Float32Array",
  "Float64Array",
  "Map",
  "WeakMap",
  "Set",
  "WeakSet",
  "Promise",
  "SharedArrayBuffer",
  "Atomics",
  "BigInt64Array",
  "BigUint64Array",
  "WeakRef",
  "FinalizationRegistry",
  "Intl",
];
export const blackListProperties = [
  "buffer",
  "slice",
  "caller",
  "callee",
  "arguments",
];

export const blackListVars = [
  "Object.bind",
  "Function.prototype.prototype",
  "Intl.DisplayNames.of",
];
