import { fileStream, makeAppendToFileWithIndentationFunction } from "./FileWriting";
import { BuiltInBindingStore } from "./Models/BuiltInBinding";

const makeAppendToFileWithIndentation = makeAppendToFileWithIndentationFunction((str)=>fileStream.write(str));

export function exportToFile(builtInBindingStore: BuiltInBindingStore, extraHardcodedTypeDefs: string) {

  fileStream.write(`///
/// THIS FILE HAS BEEN AUTOGENERATED
///
/// DO NOT EDIT MANUALLY
///

// Extra hardcoded type defs
${extraHardcodedTypeDefs.trim()}

/// Imports
import { SValues } from "../SValues/AllSValues";
import type { InstallBuiltIn } from "../BuiltIns/InstallBuiltIn";
import type { SLocalSymbolTable, SRootSymbolTable } from "../SLocalSymbolTable";
import type { SObjectValue } from "../SValues/SObjects/SObjectValue";
import type { SNormalObject } from "../SValues/SObjects/SNormalObject";
import type { SFunction } from "../SValues/SObjects/SFunction";
import type { SNumberValue } from "../SValues/SPrimitiveValues/SNumberValue";
import type { SBooleanValue } from "../SValues/SPrimitiveValues/SBooleanValue";
import type { SStringValue } from "../SValues/SPrimitiveValues/SStringValue";
import type { SUndefinedValue } from "../SValues/SPrimitiveValues/SUndefinedValue";
import type { SNullValue } from "../SValues/SPrimitiveValues/SNullValue";
import type { SBigIntValue } from "../SValues/SPrimitiveValues/SBigIntValue";
import type { SSymbolValue } from "../SValues/SPrimitiveValues/SSymbolValue";
import type { SValue } from "../SValues/SValue";;
import type { AnySFunction } from "../SValues/SObjects/SFunctionDef";
import SUserError from "../Models/SUserError";
import { encodeUnsafeStringAsJSLiteralString } from "../EncodeString";

/// Main entry point for installing all generated bindings.
export const installGeneratedBindings: InstallBuiltIn<any> = (rootSTable: SRootSymbolTable<any>) => {
`);

  const appendToInstallGeneratedBindings = makeAppendToFileWithIndentation(1);
  const builtInBindingEntriesSorted = builtInBindingStore.entries.sort((a, b) => {
    return b.sortOrder - a.sortOrder;
  });
  for (const entry of builtInBindingEntriesSorted) {
    // appendToInstallGeneratedBindings(`// builtInBinding id: ${builtInBinding.id}`);
    appendToInstallGeneratedBindings("// private implementation..." + entry.sortOrder);
    if (entry.implementationModal !== undefined) {
      const implementationCode = entry.generatedImplementationCode();
      // appendToInstallGeneratedBindings(`const ${entry.privateName}: ${entry.sType} = ${implementationCode};`);
      appendToInstallGeneratedBindings(`const ${entry.privateName} = ${implementationCode};`);
    } else {
      appendToInstallGeneratedBindings(`// Cannot make private binding for "${entry.privateName} as no implementation code was found.`);
    }
  }
  for (const entry of builtInBindingEntriesSorted) {
    if (entry.globalVariableName !== undefined) {
      appendToInstallGeneratedBindings(`rootSTable.assign("${entry.globalVariableName}", ${entry.privateName} as SValue<any>, "const");`);
    }
  }
  for (const entry of builtInBindingEntriesSorted) {
    if (entry.internalName !== undefined) {
      appendToInstallGeneratedBindings(`rootSTable.sGlobalProtocols.${entry.internalName} = ${entry.privateName} as SNormalObject<any>;`); 
    }
  }

  fileStream.write(`
};`); 
}